#!/bin/bash

print_usage() {
    echo "usage: script [OPTIONS] FILE"
    echo ""
    echo "options:"
    echo "  -h            show this help message and exit"
    echo "  -k CLUSTERS   number of clusters"
    echo "  -n SAMPLES    sample size"
    echo "  -m MULT       initial lower bound multiplier"
}

# defaults
n=5
m=1.25

while getopts ":hk:n:m:" opt; do
    case $opt in
        h)
            print_usage
            exit 1
            ;;
        k)
            k=$OPTARG
            ;;
        n)
            n=$OPTARG
            ;;
        m)
            m=$OPTARG
            ;;
        \?)
            echo "invalid option: -$OPTARG" >&2
            print_usage
            exit 1
            ;;
        :)
            echo "option -$OPTARG requires an argument." >&2
            print_usage
            exit 1
            ;;
    esac
done

if [ $(( $# - $OPTIND )) -lt 0 ]; then
    echo "missing dataset, stopping"
    exit 1
fi

dataset=${@:$OPTIND:1}
data_folder="datasets/$dataset"
data_file="$data_folder/$dataset.dat"

if [[ !(-f $data_file) ]]; then
    echo "no such file or directory: $data"
    exit 1
fi

if [[ -f $data_folder/yy.dat ]]; then
    rm $data_folder/yy.dat
fi

if [[ -f $data_folder/yy_acc.dat ]]; then
    rm $data_folder/yy_acc.dat
fi

cmd="taskset 8 ./kmeans-dbg $data_file -q"
if [[ !(-z $k) ]]; then
    cmd+=" -k $k"
fi

for (( i=1; i <= $n; i++));
do
    seed=$RANDOM
    yy=`$cmd -s $seed -a yy`
    yy_time=`echo $yy | cut -f1 -d' '`
    yy_clst=`echo $yy | cut -f2 -d' '`
    # yy_clst=`echo $yy | cut -f2 -d' ' | sed -e 's/./&,/g' -e '$ s/.$//'`

    yy_acc=`$cmd -s $seed -a yy -m $m`
    yy_acc_time=`echo $yy_acc | cut -f1 -d' '`
    yy_acc_clst=`echo $yy_acc | cut -f2 -d' '`
    # yy_acc_clst=`echo $yy_acc | cut -f2 -d' ' | sed -e 's/./&,/g' -e '$ s/.$//'`

    echo "$yy_time,$yy_clst" >> $data_folder/yy.dat
    echo "$yy_acc_time,$yy_acc_clst" >> $data_folder/yy_acc.dat

    # gain=echo `echo "scale=4;1 - ($yy_acc_time / $yy_time)" | bc`
    # similarity=`Rscript randindex.r --args $yy_clst $yy_acc_clst | cut -f2 -d' '`
    # echo "$gain,$similarity,$m" >> $data_folder/processed.dat
done
