#!/usr/bin/env python
import subprocess as sp
import argparse
import random
import errno
import os


def remove_file(filename):
    try:
        os.remove(filename)
    except OSError as e:
        # errno.ENOENT = no such file or directory
        if e.errno != errno.ENOENT:
            raise  # re-raise exception if a different error occured


def float_range(start, stop=None, step=1.0, error=0.00000001):
    if stop is None:
        stop = start
        start = 0.0
    if step <= 0:
        while start < (stop + error):
            yield start
            start += step
    else:
        while start < (stop - error):
            yield start
            start += step

parser = argparse.ArgumentParser()
parser.add_argument('-d', action='store', dest='data',
                    required=True, help='dataset name')
parser.add_argument('-k', action='store', dest='clusters',
                    required=True, help='number of clusters')
parser.add_argument('-n', action='store', dest='iterations',
                    default='10',  help='sample size')
parser.add_argument('-o', action='store', dest='outfile',
                    default='processed',  help='outfile name')
args = parser.parse_args()

random.seed()

data_folder = "../datasets/" + args.data + "/"
data = data_folder + args.data + ".dat"
yy_args = "../kmeans " + data + " -q -a yy -k " + args.clusters + " -s "

outfile = data_folder + args.outfile + ".dat"
remove_file(outfile)

for mult in [m for m in float_range(1.1, 2.1, 0.1)]:
    res = ([], [], [])
    res2 = ([], [], [])
    for i in range(int(args.iterations)):
        seed = random.getrandbits(64)

        yy = sp.getoutput(yy_args + str(seed))
        yy_m = sp.getoutput(yy_args + str(seed) + " -m " + str(mult))

        yy = str.splitlines(yy)
        yy_m = str.splitlines(yy_m)

        # computa o ganho
        res[0].append(float(yy_m[0]) - float(yy[0]))
        # rand index comparando os agrupamentos
        res[1].append(sp.getoutput("Rscript randindex.r --args " + yy[1] + " " + yy_m[1]))
        # multiplicador utilizado
        res[2].append(mult)

    res = zip(res[0], res[1], res[2])
    with open(outfile, 'a') as f:
        for col in res:
            f.write("{0},{1},{2}\n".format(*col))
