#! /bin/sh

# compares the output of lloyd k-means with that of yinyang k-means

# $1 - dataset
# $2 - #clusters
# $3 - #iterations

function print_usage() {
    echo "usage: compare <dataset> <#clusters> <#iterations>"
}

if [[ "$1" == "h" || "$1" == "help" || "$1" == "-h" || "$1" == "--help" ]]
then
    print_usage
    exit
fi

if [[ -z $1 ]]
then
    echo "no dataset specified, stopping"
    print_usage
    exit
fi

K="-k $2"
if [[ -z $2 ]]
then
    K=""
fi

iterations=1
if [[ -n $2 ]]
then
    iterations=$2
fi

for i in `seq 1 $iterations`;
do
    r=$RANDOM
    ll=`../kmeans ../datasets/$1/$1.dat $K -s $r -q | tail -1`
    yy=`../kmeans ../datasets/$1/$1.dat $K -s $r -q -a yy | tail -1`

    if [[ $ll != $yy ]];
    then
        echo "Erro em $i, seed: $r"
    fi
done
