#! /bin/sh

# $1 - dataset
# $2 - # of clusters
# $3 - # of iterations
# $4 - lb mult

function print_usage() {
    echo "usage: generate-output <dataset> <#clusters> <#iterations> <lb_mult>"
}

if [[ "$1" == "h" || "$1" == "help" || "$1" == "-h" || "$1" == "--help" ]]
then
    print_usage
    exit
fi

K="-k $2"

if [[ -z $1 ]]
then
    echo "no dataset specified, stopping"
    print_usage
    exit
fi

if [[ -z $3 ]]
then
    echo "no number of iterations specified, stopping"
    print_usage
    exit
fi

if [[ -z $4 ]]
then
    echo "no multiplier specified, stopping"
    print_usage
    exit
fi

if [[ -z $2 ]]
then
    K=""
fi

if [[ ! -d out ]]
then
    mkdir out
fi

if [[ -f out/yy ]]
then
    rm out/yy
fi

if [[ -f out/yy_mult ]]
then
    rm out/yy_mult
fi

for i in `seq 1 $3`
do
    r=$RANDOM
    ../kmeans ../datasets/$1/$1.dat $K -s $r -q -a yy >> out/yy
    ../kmeans ../datasets/$1/$1.dat $K -s $r -q -a yy -m $4 >> out/yy_mult
done
